import { exec } from 'child_process';
import * as constants from './constants';

// Executes the Python script or exe generated by the Python script with flags containing
// the videoPath, savePath, epochLength, threshold, and whether to run OpenPose or not.
export function processVideo(afterFunction: any, options?: any) {
	const videoPath = localStorage.getItem('videoPath');
	const savePath = localStorage.getItem('savePath');
	let openpose = 1;
	let epochLength = constants.epochLength;
	let headThreshold = constants.generalThresholds.Head;
	let armsThreshold = constants.generalThresholds.Arms;
	let legsThreshold = constants.generalThresholds.Legs;
	let feetThreshold = constants.generalThresholds.Feet;
	if (options !== undefined) {
		openpose = 0;
		epochLength = options.epochLength;
		headThreshold = options.Head;
		armsThreshold = options.Arms;
		legsThreshold = options.Legs;
		feetThreshold = options.Feet;
	}
	// exec(
	// 	`python ./src/py/processing_script.py "${videoPath}" "${savePath}" ${openpose} ${headThreshold} ${armsThreshold} ${legsThreshold} ${feetThreshold} ${epochLength}`,
	// 	afterFunction
	// );
	exec(
		`processing_script.exe "${videoPath}" "${savePath}" ${openpose} ${headThreshold} ${armsThreshold} ${legsThreshold} ${feetThreshold} ${epochLength}`,
		afterFunction
	);
}

export function deidentifyVideo(afterFunction: any) {
	const videoPath = localStorage.getItem('videoPath');
	const savePath = localStorage.getItem('savePath');
	exec(`python ./src/py/deidentification.py "${videoPath}" "${savePath}"`, afterFunction);
}
